/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/
# include <stdio.h>
# include <math.h>

int num_of_divisors(long int n)
{
    long int num = 0;
    for (long int i = 1; i <= (int)pow(n, 0.5); i++)
    {
        if (n % i == 0)
        {
            num += 2;
        }
    }

    if ((int)pow(n, 0.5) * (int)pow(n, 0.5) == num)
    {
        num--;
    }

    return num;
}

int main()
{
    long int n = 1;

    while (num_of_divisors(n*(n+1)/2) < 500)
    {
        n++;
    }
    printf("%d\n", n*(n+1)/2);
}
